# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tsampi
  name: tsampi-service
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
    targetPort: 8443
  - port: 80
    protocol: TCP
    name: http
    targetPort: 8080
  selector:
    app: tsampi
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 104.154.101.64
